services:
    db:
       image: postgres
       env_file:
          - .env_db
       volumes:
          - db_data:/var/lib/postgresql
       networks:
          - app_network

    redis:
      image: redis:6.2-alpine
      volumes:
        - redis_data:/data
      networks:
        - app_network
      depends_on:
        - db
          
    app:
        build: .
        container_name: flask_app
        ports:
            - 5000:8000
        env_file:
            - .env
        networks:
            - app_network
        depends_on:
            - db
        restart: on-failure
networks:
   app_network:
     driver: bridge
        
volumes:
  db_data:
  redis_data: