name: App_Build

on: 
    push:
     branches:
        - main

jobs:
    Deploying_App:
        runs-on: ubuntu-latest
        steps:
        - name: Code Checkout
          uses: actions/checkout@v7
        - name: BUilding Image
          run: docker compose up -d
        - name: smoke test
          run: |
            sleep 5
            curl -Iv localhost:5000

